import React, { useRef, useEffect, useState, useCallback } from 'react';
import { RotateCcw, Play } from 'lucide-react';
import TopicLayoutContainer from '../../TopicLayoutContainer';

interface CarnotEngineLabProps {
    topic: any;
    onExit: () => void;
}

const R_const = 8.314;
const gamma_const = 1.4;
const n_const = 1;

function isothermP_calc(V: number, T: number) { return (n_const * R_const * T) / V; }
function adiabaticP_calc(V: number, P0: number, V0: number) { return P0 * Math.pow(V0 / V, gamma_const); }

const STEP_INFO = [
    { title: 'System Ready', short: 'CONFIGURE TEMPERATURES AND START THE CARNOT CYCLE.', detail: '' },
    {
        title: 'STEP 1: ISOTHERMAL EXPANSION',
        short: 'GAS ABSORBS HEAT Q₁ FROM HOT SOURCE AT T₁.',
        detail: 'The gas is in contact with the HOT reservoir. It expands slowly at constant T₁, so internal energy stays constant and all heat absorbed (Q₁) is converted to work.',
    },
    {
        title: 'STEP 2: ADIABATIC EXPANSION',
        short: 'GAS EXPANDS FURTHER, TEMPERATURE DROPS TO T₂.',
        detail: 'The gas is now INSULATED. It keeps expanding, doing work by consuming its own internal energy, which causes the temperature to fall to T₂.',
    },
    {
        title: 'STEP 3: ISOTHERMAL COMPRESSION',
        short: 'GAS REJECTS HEAT Q₂ TO COLD SINK AT T₂.',
        detail: 'The gas is placed on the COLD reservoir and compressed. Heat generated by work is rejected to the sink, keeping temperature at T₂.',
    },
    {
        title: 'STEP 4: ADIABATIC COMPRESSION',
        short: 'GAS COMPRESSED BACK TO INITIAL STATE AT T₁.',
        detail: 'INSULATED again. Compression raises the internal energy and temperature back to the initial state T₁, closing the cycle.',
    },
    {
        title: 'CYCLE COMPLETE!',
        short: 'NET WORK W = Q₁ − Q₂ (AREA ENCLOSED BY THE CYCLE).',
        detail: 'Efficiency η = 1 − T₂/T₁ is the maximum possible efficiency for any heat engine between these temperatures.',
    },
];

const CarnotEngineLab: React.FC<CarnotEngineLabProps> = ({ topic, onExit }) => {
    const [t1, setT1] = useState(800);
    const [t2, setT2] = useState(300);
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const animRef = useRef<number>(0);

    const [phase, setPhase] = useState(0); 
    const phaseRef = useRef(0);
    const progRef = useRef(0);
    const isAutoRef = useRef(false);
    const replayStepRef = useRef(0);

    useEffect(() => { phaseRef.current = phase; }, [phase]);

    // Volumes at corners
    const V1 = 1.0, V2 = 2.4;
    const P1 = isothermP_calc(V1, t1), P2 = isothermP_calc(V2, t1);
    const V3 = V2 * Math.pow(t1 / t2, 1 / (gamma_const - 1));
    const V4 = V1 * Math.pow(t1 / t2, 1 / (gamma_const - 1));
    const P3 = isothermP_calc(V3, t2), P4 = isothermP_calc(V4, t2);

    const Q1 = n_const * R_const * t1 * Math.log(V2 / V1);
    const Q2 = n_const * R_const * t2 * Math.log(V3 / V4);
    const W_net = Q1 - Q2;
    const efficiency = 1 - t2 / t1;

    // ResizeObserver
    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const parent = canvas.parentElement;
        if (!parent) return;
        const resizeObserver = new ResizeObserver(() => {
            canvas.width = parent.clientWidth;
            canvas.height = parent.clientHeight;
        });
        resizeObserver.observe(parent);
        canvas.width = parent.clientWidth;
        canvas.height = parent.clientHeight;
        return () => resizeObserver.disconnect();
    }, []);

    const startCycle = () => { progRef.current = 0; isAutoRef.current = true; replayStepRef.current = 0; setPhase(1); };
    const resetCycle = () => { progRef.current = 0; isAutoRef.current = false; replayStepRef.current = 0; setPhase(0); };
    const replayStep = (s: number) => { replayStepRef.current = s; progRef.current = s - 1; isAutoRef.current = true; setPhase(s); };

    const draw = useCallback(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        const W = canvas.width, H = canvas.height;
        if (W < 10 || H < 10) { animRef.current = requestAnimationFrame(draw); return; }

        const cp = phaseRef.current;
        const isReplay = replayStepRef.current > 0;

        // Progress
        if (isAutoRef.current && cp >= 1 && cp <= 4) {
            progRef.current += 0.005;
            const sp = progRef.current - (cp - 1);
            if (sp >= 1) {
                if (isReplay) { isAutoRef.current = false; setPhase(5); }
                else if (cp < 4) setPhase(cp + 1);
                else { isAutoRef.current = false; setPhase(5); }
            }
        }

        const gp = progRef.current;
        const getProg = (s: number) => {
            if (isReplay && replayStepRef.current !== s) return s < replayStepRef.current ? 1 : 0;
            return Math.max(0, Math.min(1, gp - (s - 1)));
        };

        ctx.clearRect(0, 0, W, H);
        ctx.fillStyle = '#f8fafc'; // Soft White
        ctx.fillRect(0, 0, W, H);

        // DYNAMIC VIEWPORT SCALING (Laptop vs Smartboard)
        const scale = W < 1000 ? 1.0 : (W > 1500 ? 1.3 : 1.0 + (W - 1000) * 0.0006);
        const fs = (base: number) => Math.max(10, Math.min(base * scale, W * 0.025, H * 0.045));
        const pad = Math.min(W * 0.03, H * 0.035, scale * 24);

        const cylW_val = W * 0.20, graphW_val = W * 0.50, statsW_val = W * 0.20;
        const cylX_val = pad, graphX_val = cylX_val + cylW_val + pad * 2, statsX_val = graphX_val + graphW_val + pad * 2;

        let currentV = V1, currentT = t1;
        const p1 = getProg(1), p2 = getProg(2), p3 = getProg(3), p4 = getProg(4);
        if (cp === 0) { currentV = V1; currentT = t1; }
        else if (cp === 1) { currentV = V1 + (V2 - V1) * p1; currentT = t1; }
        else if (cp === 2) { currentV = V2 + (V3 - V2) * p2; currentT = t1 + (t2 - t1) * p2; }
        else if (cp === 3) { currentV = V3 + (V4 - V3) * p3; currentT = t2; }
        else if (cp === 4) { currentV = V4 + (V1 - V4) * p4; currentT = t2 + (t1 - t2) * p4; }
        else {
            const rs = replayStepRef.current;
            if (rs === 1) { currentV = V2; currentT = t1; }
            else if (rs === 2) { currentV = V3; currentT = t2; }
            else if (rs === 3) { currentV = V4; currentT = t2; }
            else { currentV = V1; currentT = t1; }
        }

        // --- CYLINDER ---
        const cylH_val = H * 0.45;
        const cylPad_val = cylW_val * 0.1;
        const pistonNorm_val = (currentV - V1) / (V3 * 1.1 - V1);
        const pistonY_val = pad * 5 + cylH_val - pistonNorm_val * (cylH_val - 40);

        ctx.strokeStyle = '#94a3b8'; ctx.lineWidth = 3;
        ctx.strokeRect(cylX_val + cylPad_val, pad * 5, cylW_val - cylPad_val * 2, cylH_val);
        
        const tempRel = (currentT - t2) / (t1 - t2);
        const gR_val = Math.round(59 + tempRel * 180), gB_val = Math.round(235 - tempRel * 170);
        ctx.fillStyle = `rgba(${gR_val}, 100, ${gB_val}, 0.3)`;
        ctx.fillRect(cylX_val + cylPad_val + 3, pistonY_val, cylW_val - cylPad_val * 2 - 6, (pad * 5 + cylH_val) - pistonY_val - 3);

        ctx.fillStyle = '#475569'; ctx.strokeStyle = '#0f172a';
        roundRect(ctx, cylX_val + cylPad_val - 5, pistonY_val - 12, cylW_val - cylPad_val * 2 + 10, 16, 5); ctx.fill(); ctx.stroke();
        
        ctx.fillStyle = '#0f172a'; ctx.font = `bold ${fs(14)}px sans-serif`; ctx.textAlign = 'center';
        ctx.fillText('WORKING SUBSTANCE', cylX_val + cylW_val / 2, pad * 4);
        ctx.fillStyle = '#64748b'; ctx.font = `bold ${fs(12)}px monospace`;
        ctx.fillText(`${currentV.toFixed(2)}L | ${Math.round(currentT)}K`, cylX_val + cylW_val / 2, pad * 4 + fs(14) + 2);

        // Reservoir Base
        let resColor_val = '#f1f5f9', resLabel_val = 'STANDBY';
        let lblColor_val = '#64748b';
        if (cp === 1) { resColor_val = '#dc2626'; resLabel_val = 'HOT SOURCE (T₁)'; lblColor_val = '#ffffff'; }
        else if (cp === 3) { resColor_val = '#2563eb'; resLabel_val = 'COLD SINK (T₂)'; lblColor_val = '#ffffff'; }
        else if (cp === 2 || cp === 4) { resColor_val = '#475569'; resLabel_val = 'ADIABATIC'; lblColor_val = '#ffffff'; }
        else if (cp === 5) { resColor_val = '#16a34a'; resLabel_val = 'COMPLETE'; lblColor_val = '#ffffff'; }
        ctx.fillStyle = resColor_val; roundRect(ctx, cylX_val + cylPad_val - 12, pad * 5 + cylH_val + 8, cylW_val - cylPad_val * 2 + 24, 35, 8); ctx.fill();
        ctx.fillStyle = lblColor_val; ctx.font = `bold ${fs(12)}px sans-serif`;
        ctx.fillText(resLabel_val, cylX_val + cylW_val / 2, pad * 5 + cylH_val + pad * 1.3);

        // --- P-V GRAPH (NCERT Style — power V scaling, linear P) ---
        const gh_val = H * 0.55, gw_val = graphW_val - pad * 5;
        const gx_val = graphX_val + pad * 3.5, gy_val = pad * 5.5;

        ctx.fillStyle = '#ffffff'; roundRect(ctx, graphX_val, pad * 3, graphW_val, gh_val + pad * 5, 18); ctx.fill();
        ctx.strokeStyle = '#e2e8f0'; ctx.lineWidth = 1.5; roundRect(ctx, graphX_val, pad * 3, graphW_val, gh_val + pad * 5, 18); ctx.stroke();

        // Axes
        ctx.strokeStyle = '#1e293b'; ctx.lineWidth = 2.5;
        ctx.beginPath(); ctx.moveTo(gx_val, gy_val - 8); ctx.lineTo(gx_val, gy_val + gh_val); ctx.lineTo(gx_val + gw_val + 8, gy_val + gh_val); ctx.stroke();
        // Arrowheads
        ctx.fillStyle = '#1e293b';
        ctx.beginPath(); ctx.moveTo(gx_val - 5, gy_val - 4); ctx.lineTo(gx_val, gy_val - 14); ctx.lineTo(gx_val + 5, gy_val - 4); ctx.fill();
        ctx.beginPath(); ctx.moveTo(gx_val + gw_val + 4, gy_val + gh_val - 5); ctx.lineTo(gx_val + gw_val + 14, gy_val + gh_val); ctx.lineTo(gx_val + gw_val + 4, gy_val + gh_val + 5); ctx.fill();

        ctx.fillStyle = '#1e293b'; ctx.font = `bold ${fs(15)}px "Inter", sans-serif`; ctx.textAlign = 'center';
        ctx.fillText('P-V Diagram of Heat Engine', graphX_val + graphW_val / 2, pad * 4.2);

        ctx.fillStyle = '#475569'; ctx.font = `bold ${fs(13)}px "Inter", sans-serif`;
        ctx.fillText('Volume  →', gx_val + gw_val / 2, gy_val + gh_val + pad * 2.8);
        ctx.save(); ctx.translate(gx_val - pad * 2.2, gy_val + gh_val / 2); ctx.rotate(-Math.PI / 2);
        ctx.fillText('Pressure  →', 0, 0); ctx.restore();

        // POWER SCALING on V (spreads small V, compresses large V) + LINEAR on P
        // This gives proper hyperbolic curve shapes like the NCERT diagram
        const vPow = 0.4; // power exponent — lower = more spread
        const allV = [V1, V2, V3, V4];
        const allP = [P1, P2, P3, P4];
        const vPowMax = Math.pow(Math.max(...allV) * 1.15, vPow);
        const vPowMin = Math.pow(Math.min(...allV) * 0.7, vPow);
        const pMax = Math.max(...allP) * 1.12;

        const sv_val = (v: number) => gx_val + ((Math.pow(v, vPow) - vPowMin) / (vPowMax - vPowMin)) * gw_val;
        const sp_val = (p: number) => gy_val + gh_val - (p / pMax) * gh_val;

        // Light grid
        ctx.strokeStyle = '#f1f5f9'; ctx.lineWidth = 1;
        for (let i = 1; i <= 4; i++) {
            const ly = gy_val + (gh_val / 5) * i;
            ctx.beginPath(); ctx.moveTo(gx_val, ly); ctx.lineTo(gx_val + gw_val, ly); ctx.stroke();
            const lx = gx_val + (gw_val / 5) * i;
            ctx.beginPath(); ctx.moveTo(lx, gy_val); ctx.lineTo(lx, gy_val + gh_val); ctx.stroke();
        }

        const drawCurve_val = (step: number, vS: number, vE: number, pFn: (v: number) => number, color: string, _rev: boolean) => {
            const p_val = getProg(step); if (p_val <= 0 && !isReplay && cp < step) return;
            const active_val = (isReplay && replayStepRef.current === step) || (cp === step && !isReplay);
            ctx.strokeStyle = color; ctx.lineWidth = active_val ? 5 : 3;
            ctx.globalAlpha = (isReplay && !active_val && cp === 5) ? 0.4 : 1.0;
            ctx.beginPath();
            const limit_val = vS + (vE - vS) * p_val;
            const steps = 80;
            for (let i = 0; i <= steps; i++) {
                const t = i / steps;
                const v = vS + (vE - vS) * t * (p_val >= 1 ? 1 : p_val);
                if (vE > vS ? v > (p_val >= 1 ? vE : limit_val) : v < (p_val >= 1 ? vE : limit_val)) break;
                const px = sv_val(v), py = sp_val(pFn(v));
                i === 0 ? ctx.moveTo(px, py) : ctx.lineTo(px, py);
            }
            ctx.stroke();

            // Arrowhead at midpoint
            if (p_val > 0.5) {
                const midV = vS + (vE - vS) * 0.5;
                const midP = pFn(midV);
                const dv = (vE - vS) * 0.02;
                const nextV = midV + dv;
                const nextP = pFn(nextV);
                const angle = Math.atan2(sp_val(nextP) - sp_val(midP), sv_val(nextV) - sv_val(midV));
                const hl = 12;
                ctx.fillStyle = color; ctx.beginPath();
                ctx.moveTo(sv_val(midV), sp_val(midP));
                ctx.lineTo(sv_val(midV) - hl * Math.cos(angle - 0.45), sp_val(midP) - hl * Math.sin(angle - 0.45));
                ctx.lineTo(sv_val(midV) - hl * Math.cos(angle + 0.45), sp_val(midP) - hl * Math.sin(angle + 0.45));
                ctx.closePath(); ctx.fill();
            }
            ctx.globalAlpha = 1.0;
        };

        drawCurve_val(1, V1, V2, (v) => isothermP_calc(v, t1), '#dc2626', false);
        drawCurve_val(2, V2, V3, (v) => adiabaticP_calc(v, P2, V2), '#d97706', false);
        drawCurve_val(3, V3, V4, (v) => isothermP_calc(v, t2), '#2563eb', true);
        drawCurve_val(4, V4, V1, (v) => adiabaticP_calc(v, P4, V4), '#7c3aed', true);

        // ─── POINT LABELS (1, 2, 3, 4) — positioned OUTSIDE the cycle ───
        const labelFont = Math.max(15, gw_val * 0.045);
        const dotR = 7;
        const pointData = [
            { v: V1, p: P1, label: '1', align: 'right' as const, ox: -18, oy: -14, step: 1 },
            { v: V2, p: P2, label: '2', align: 'left' as const, ox: 18, oy: -6, step: 1 },
            { v: V3, p: P3, label: '3', align: 'left' as const, ox: 18, oy: 6, step: 2 },
            { v: V4, p: P4, label: '4', align: 'right' as const, ox: -18, oy: 14, step: 3 },
        ];
        pointData.forEach(c => {
            if (cp < c.step && !isReplay) return;
            if (getProg(c.step) <= 0 && !isReplay && cp !== 5) return;

            const px = sv_val(c.v), py = sp_val(c.p);
            // Filled dot with white ring
            ctx.fillStyle = '#16a34a';
            ctx.beginPath(); ctx.arc(px, py, dotR, 0, Math.PI * 2); ctx.fill();
            ctx.strokeStyle = '#ffffff'; ctx.lineWidth = 2.5;
            ctx.beginPath(); ctx.arc(px, py, dotR, 0, Math.PI * 2); ctx.stroke();
            ctx.strokeStyle = '#16a34a'; ctx.lineWidth = 1.5;
            ctx.beginPath(); ctx.arc(px, py, dotR + 2, 0, Math.PI * 2); ctx.stroke();

            ctx.fillStyle = '#0f172a'; ctx.font = `bold ${labelFont}px "Inter", sans-serif`;
            ctx.textAlign = c.align === 'left' ? 'left' : 'right';
            ctx.fillText(c.label, px + c.ox, py + c.oy + labelFont * 0.35);
        });

        // ─── PROCESS LABELS — positioned OUTSIDE the cycle edges ───
        if (cp >= 1 || isReplay) {
            const procFont = Math.max(12, gw_val * 0.028);

            const drawEdgeLabel = (step: number, label: string, x: number, y: number, align: CanvasTextAlign) => {
                if (getProg(step) < 0.5 && cp !== 5 && !isReplay) return;
                ctx.fillStyle = '#1e293b'; ctx.font = `italic 600 ${procFont}px "Inter", sans-serif`;
                ctx.textAlign = align;
                ctx.fillText(label, x, y);
            };

            // I: Isothermal — ABOVE the top curve, centered between points 1 and 2
            const i1x = (sv_val(V1) + sv_val(V2)) / 2;
            const i1y = sp_val(isothermP_calc((V1 + V2) / 2, t1)) - procFont * 1.8;
            drawEdgeLabel(1, 'I  Isothermal expansion', i1x, i1y, 'center');

            // II: Adiabatic — RIGHT of the right curve, between points 2 and 3
            const i2v = V2 + (V3 - V2) * 0.6;
            const i2x = sv_val(i2v) + procFont * 3;
            const i2y = sp_val(adiabaticP_calc(i2v, P2, V2));
            drawEdgeLabel(2, 'II  Adiabatic expansion', i2x, i2y, 'left');

            // III: Isothermal — BELOW the bottom curve, centered between points 3 and 4
            const i3x = (sv_val(V3) + sv_val(V4)) / 2;
            const i3y = sp_val(isothermP_calc((V3 + V4) / 2, t2)) + procFont * 2.5;
            drawEdgeLabel(3, 'III  Isothermal compression', i3x, i3y, 'center');

            // IV: Adiabatic — LEFT of the left curve, between points 4 and 1
            const i4v = V4 + (V1 - V4) * 0.4;
            const i4x = sv_val(i4v) - procFont * 3;
            const i4y = sp_val(adiabaticP_calc(i4v, P4, V4));
            drawEdgeLabel(4, 'IV  Adiabatic compression', i4x, i4y, 'right');

            // Temperature labels on right — T₁=T₂=T_high and T₃=T₄=T_low
            if (cp === 5 || isReplay) {
                ctx.fillStyle = '#dc2626'; ctx.font = `bold ${Math.max(11, procFont * 0.9)}px "Inter", sans-serif`;
                ctx.textAlign = 'left';
                const tHighY = (sp_val(P1) + sp_val(P2)) / 2;
                ctx.fillText(`T₁ = ${t1}K`, gx_val + gw_val - procFont * 5, tHighY);
                ctx.fillStyle = '#2563eb';
                const tLowY = (sp_val(P3) + sp_val(P4)) / 2;
                ctx.fillText(`T₂ = ${t2}K`, gx_val + gw_val - procFont * 5, tLowY);
            }
        }

        // ─── NET WORK DONE FILL (cycle complete) ───
        if (cp === 5 && !isReplay) {
            ctx.fillStyle = 'rgba(22, 163, 74, 0.20)';
            ctx.beginPath();
            for (let i = 0; i <= 80; i++) { const v = V1 + (V2-V1)*(i/80); i===0 ? ctx.moveTo(sv_val(v), sp_val(isothermP_calc(v,t1))) : ctx.lineTo(sv_val(v), sp_val(isothermP_calc(v,t1))); }
            for (let i = 0; i <= 80; i++) { const v = V2 + (V3-V2)*(i/80); ctx.lineTo(sv_val(v), sp_val(adiabaticP_calc(v,P2,V2))); }
            for (let i = 0; i <= 80; i++) { const v = V3 + (V4-V3)*(i/80); ctx.lineTo(sv_val(v), sp_val(isothermP_calc(v,t2))); }
            for (let i = 0; i <= 80; i++) { const v = V4 + (V1-V4)*(i/80); ctx.lineTo(sv_val(v), sp_val(adiabaticP_calc(v,P4,V4))); }
            ctx.closePath(); ctx.fill();

            // Hatching
            ctx.save(); ctx.clip();
            ctx.strokeStyle = 'rgba(22, 163, 74, 0.35)'; ctx.lineWidth = 1.5;
            for (let x = -H; x < W; x += 14) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x + H, H); ctx.stroke(); }
            ctx.restore();

            // W label in geometric center
            const ctrV = Math.pow((Math.pow(V1, vPow) + Math.pow(V2, vPow) + Math.pow(V3, vPow) + Math.pow(V4, vPow)) / 4, 1/vPow);
            const ctrP = (P1 + P2 + P3 + P4) / 4;
            ctx.fillStyle = '#15803d'; ctx.font = `bold ${fs(13)}px "Inter", sans-serif`; ctx.textAlign = 'center';
            ctx.fillText('−W_out', sv_val(ctrV), sp_val(ctrP));
        }

        if (cp >= 1 && cp <= 4) {
            let dp_val = P1;
            if (cp === 1) dp_val = isothermP_calc(currentV, t1);
            else if (cp === 2) dp_val = adiabaticP_calc(currentV, P2, V2);
            else if (cp === 3) dp_val = isothermP_calc(currentV, t2);
            else if (cp === 4) dp_val = adiabaticP_calc(currentV, P4, V4);
            ctx.fillStyle = '#0f172a'; ctx.beginPath(); ctx.arc(sv_val(currentV), sp_val(dp_val), 7, 0, Math.PI * 2); ctx.fill();
            ctx.strokeStyle = '#fff'; ctx.lineWidth = 2.5; ctx.stroke();
        }

        // --- STATS PANEL ---
        const sPH = statsW_val * 1.5;
        ctx.fillStyle = '#ffffff'; roundRect(ctx, statsX_val, pad * 3, statsW_val, sPH, 18); ctx.fill();
        ctx.strokeStyle = '#e2e8f0'; ctx.lineWidth = 1.5; roundRect(ctx, statsX_val, pad * 3, statsW_val, sPH, 18); ctx.stroke();
        
        ctx.fillStyle = '#475569'; ctx.font = `bold ${fs(12)}px sans-serif`; ctx.textAlign = 'center';
        ctx.fillText('CYCLE STATS', statsX_val + statsW_val / 2, pad * 4.2);

        const scW_val = statsW_val / 2;
        const metrics = [
            { l: 'T₁ (HOT)', v: `${t1}K`, c: '#dc2626' }, { l: 'Q₁ (IN)', v: `${Math.round(Q1)}J`, c: '#d97706' },
            { l: 'T₂ (COLD)', v: `${t2}K`, c: '#2563eb' }, { l: 'Q₂ (OUT)', v: `${Math.round(Q2)}J`, c: '#3b82f6' },
            { l: 'WORK W', v: `${Math.round(W_net)}J`, c: '#16a34a' }, { l: 'EFF η', v: `${(efficiency * 100).toFixed(1)}%`, c: '#15803d' }
        ];
        metrics.forEach((v, i) => {
            const row = Math.floor(i / 2), col = i % 2;
            const rY = pad * 5.5 + row * (sPH * 0.28);
            ctx.fillStyle = '#94a3b8'; ctx.font = `bold ${fs(9)}px sans-serif`;
            ctx.fillText(v.l, statsX_val + col * scW_val + scW_val / 2, rY);
            ctx.fillStyle = v.c; ctx.font = `bold ${fs(16)}px monospace`;
            ctx.fillText(v.v, statsX_val + col * scW_val + scW_val / 2, rY + fs(16));
        });

        // --- DESCRIPTION BOX ---
        const descY_val = pad * 5 + cylH_val + 60;
        const descH_val = H - descY_val - pad;
        if (descH_val > 50) {
            const step_info = STEP_INFO[cp];
            ctx.fillStyle = '#ffffff'; roundRect(ctx, pad, descY_val, W - pad * 2, descH_val, 20); ctx.fill();
            ctx.strokeStyle = cp === 5 ? '#16a34a' : '#e2e8f0'; ctx.lineWidth = 2; ctx.stroke();
            
            ctx.fillStyle = cp === 5 ? '#16a34a' : '#0f172a'; ctx.font = `bold ${fs(16)}px sans-serif`; ctx.textAlign = 'left';
            ctx.fillText(step_info.title, pad * 3, descY_val + fs(16) + pad * 0.8);
            ctx.fillStyle = '#475569'; ctx.font = `bold ${fs(13)}px sans-serif`;
            ctx.fillText(step_info.short, pad * 3, descY_val + fs(16) + pad * 1.8);
            
            if (descH_val > 100) {
                 ctx.fillStyle = '#64748b'; ctx.font = `${fs(12)}px sans-serif`;
                 const text = step_info.detail;
                 const words = text.split(' ');
                 let line = '';
                 let ly = descY_val + fs(16) + pad * 2.8;
                 for (let n = 0; n < words.length; n++) {
                    let testLine = line + words[n] + ' ';
                    if (ctx.measureText(testLine).width > (W - pad * 6) && n > 0) {
                        ctx.fillText(line, pad * 3, ly);
                        line = words[n] + ' ';
                        ly += fs(12) + 4;
                    } else {
                        line = testLine;
                    }
                 }
                 ctx.fillText(line, pad * 3, ly);
            }
        }

        ctx.fillStyle = '#0f172a'; ctx.font = `bold ${fs(20)}px sans-serif`; ctx.textAlign = 'left';
        ctx.fillText('Thermodynamics: The Carnot Heat Engine', pad, pad * 1.3);

        animRef.current = requestAnimationFrame(draw);
    }, [t1, t2, V2, V3, efficiency, phase]);

    useEffect(() => {
        animRef.current = requestAnimationFrame(draw);
        return () => cancelAnimationFrame(animRef.current);
    }, [draw]);

    const simulationCombo = (
        <div className="w-full h-full relative bg-slate-50 rounded-2xl overflow-hidden border border-slate-200 shadow-inner flex flex-col">
            <div className="flex-1 relative min-h-[300px]">
                <canvas ref={canvasRef} className="absolute inset-0 w-full h-full object-contain" />
            </div>
        </div>
    );

    const controlsCombo = (
        <div className="flex flex-col gap-2 md:gap-4 w-full text-slate-700 p-1 md:p-2">
            <div className="grid md:grid-cols-2 gap-3 md:gap-8">
                <div className="space-y-2 md:space-y-4 p-3 md:p-5 bg-white rounded-xl border border-slate-200 shadow-sm">
                    <label className="text-sm md:text-base font-bold text-slate-700 flex justify-between items-center mb-1">
                        <span>🔥 HOT SOURCE (T₁)</span> 
                        <span className="text-red-700 font-mono text-base md:text-lg bg-red-50 border border-red-100 px-3 py-0.5 md:py-1 rounded shadow-sm">{t1} K</span>
                    </label>
                    <input type="range" min="400" max="1000" step="10" value={t1}
                        onChange={(e) => setT1(Math.max(Number(e.target.value), t2 + 50))}
                        disabled={phase > 0 && phase < 5}
                        className="w-full accent-red-600 h-2 md:h-2.5 bg-slate-100 rounded-lg appearance-none cursor-pointer" />
                    <div className="flex justify-between text-[9px] md:text-xs font-bold text-slate-400 uppercase">
                        <span>400 K</span><span>1000 K</span>
                    </div>
                </div>
                <div className="space-y-2 md:space-y-4 p-3 md:p-5 bg-white rounded-xl border border-slate-200 shadow-sm">
                    <label className="text-sm md:text-base font-bold text-slate-700 flex justify-between items-center mb-1">
                        <span>❄ COLD SINK (T₂)</span> 
                        <span className="text-blue-700 font-mono text-base md:text-lg bg-blue-50 border border-blue-100 px-3 py-0.5 md:py-1 rounded shadow-sm">{t2} K</span>
                    </label>
                    <input type="range" min="100" max="600" step="10" value={t2}
                        onChange={(e) => setT2(Math.min(Number(e.target.value), t1 - 50))}
                        disabled={phase > 0 && phase < 5}
                        className="w-full accent-blue-600 h-2 md:h-2.5 bg-slate-100 rounded-lg appearance-none cursor-pointer" />
                    <div className="flex justify-between text-[9px] md:text-xs font-bold text-slate-400 uppercase">
                        <span>100 K</span><span>600 K</span>
                    </div>
                </div>
            </div>

            <div className="flex flex-wrap gap-2 md:gap-4 items-center justify-center mt-1 md:mt-2">
                {phase === 0 ? (
                    <button onClick={startCycle} className="flex items-center gap-2 md:gap-3 px-8 md:px-12 py-3 md:py-5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl md:rounded-2xl shadow-lg transition-all font-bold text-sm md:text-lg active:scale-95">
                        <Play size={20} className="md:w-[22px] md:h-[22px]" /> START CARNOT CYCLE
                    </button>
                ) : phase === 5 ? (
                    <div className="flex flex-wrap gap-2 md:gap-3 justify-center">
                        {[1, 2, 3, 4].map(s => (
                            <button key={s} onClick={() => replayStep(s)} className="px-3 md:px-5 py-2 md:py-3 bg-white hover:bg-slate-50 text-slate-700 rounded-xl border border-slate-200 text-[10px] md:text-sm font-bold transition-all shadow-md active:scale-95">
                                STEP {s}
                            </button>
                        ))}
                        <button onClick={resetCycle} className="flex items-center gap-2 px-4 md:px-8 py-2 md:py-3 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-xl border border-slate-200 text-[10px] md:text-sm font-bold shadow-sm active:scale-95">
                            <RotateCcw size={16} className="md:w-[18px] md:h-[18px]" /> RESET
                        </button>
                    </div>
                ) : (
                    <div className="text-xs md:text-base font-bold text-emerald-600 animate-pulse bg-emerald-50 px-6 md:px-10 py-3 md:py-4 rounded-xl md:rounded-2xl border border-emerald-100 shadow-md flex items-center gap-2 md:gap-4">
                        <span className="w-2 h-2 md:w-3 md:h-3 bg-emerald-500 rounded-full"></span>
                        EXECUTING CARNOT CYCLE: STAGE {phase} / 4
                    </div>
                )}
            </div>
        </div>
    );

    return (
        <TopicLayoutContainer topic={topic} onExit={onExit}
            SimulationComponent={simulationCombo} ControlsComponent={controlsCombo} />
    );
};

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
    ctx.beginPath(); ctx.moveTo(x + r, y); ctx.lineTo(x + w - r, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + r); ctx.lineTo(x + w, y + h - r);
    ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h); ctx.lineTo(x + r, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - r); ctx.lineTo(x, y + r);
    ctx.quadraticCurveTo(x, y, x + r, y); ctx.closePath();
}

export default CarnotEngineLab;
